import Foundation

enum BundledStories {
    static func pick() -> String {
        all.randomElement() ?? all[0]
    }

    static let all: [String] = [

        // 1 — The municipal library after closing
        """
        The last of the overhead lights had been switched off perhaps twenty minutes ago, or perhaps longer, it was difficult to say with any certainty, and the library had settled into that particular kind of quiet that only very large rooms with very high ceilings seem capable of producing. The carpet, a dull burgundy that had been installed sometime in the early nineties and had faded unevenly in patches near the windows, absorbed whatever small sounds remained. A heating duct somewhere behind the reference section emitted a low, almost inaudible hum that rose and fell in no particular pattern. The books on their shelves stood in the darkness in the same order they had occupied for years, organized by a system that most of the regular borrowers had never needed to fully understand but that the head librarian, Mrs. Alvarez, could navigate without looking. The card catalog, which had not been actively used since the computer terminals were installed, occupied a corner near the periodicals. Its small wooden drawers, each with a tarnished brass pull, remained closed. Outside the tall windows on the east side of the building, the parking lot was empty except for a single shopping cart someone had left near the bicycle rack, its metal frame catching a thin stripe of light from the streetlamp on Elm Avenue. The cart did not move. A moth had found its way inside sometime before closing and was now resting on the spine of a large atlas in the geography section, its wings flat against the cloth binding. The atlas was open to no particular page. A drinking fountain in the hallway near the restrooms made a faint mechanical click, the same click it made every forty-five minutes or so, a function of some internal pressure valve that the maintenance staff had noted in a work order three years prior but had not found occasion to address. The water in the fountain was cold and very still. On the circulation desk, a rubber stamp sat beside its ink pad, both of them perfectly dry. A few paper clips had been arranged near the edge of the desk in a loose cluster, not quite a line and not quite a pile, the way objects accumulate in a place where people stand and think and set things down without noticing. In the children's section, a small wooden chair had been left pulled slightly away from one of the low tables, its position suggesting someone had stood up in a hurry, though whoever it was had been gone for hours now. The illustrated books on the lowest shelf had their spines facing outward in the ordinary way, their titles and pictures invisible in the dark. Somewhere near the back of the building, the furnace made a long slow sound and then was quiet again.
        """,

        // 2 — A petrol station at 2am
        """
        The forecourt lights were the bright, flat kind that cast no particular shadow, and they hummed very faintly in the way that all fluorescent lights hum when there is no other sound to cover it. The attendant inside the kiosk was reading something, a magazine or possibly a paperback, it was not possible to tell from a distance, and he turned a page at long intervals and did not look up. The pumps stood in their numbered order along the concrete apron, their digital displays dark and waiting. A yellow plastic bag had lodged itself against the base of pump three and was pressing softly against it, moved slightly by the draft from passing vehicles on the highway, which ran parallel to the forecourt at a distance of perhaps thirty meters. The highway was not busy. An articulated lorry passed at intervals of several minutes, its lights sweeping across the overhead canopy and then receding, the engine sound arriving slightly after the lights and fading in a long diminuendo. A wire rack near the kiosk door held newspapers from the morning edition, their front pages faced outward behind a clear plastic panel, the headlines already half a day old. A moth circled one of the overhead lights in a wide ellipse, not touching the casing. There was a small laminated card attached to the pump closest to the highway entrance explaining the procedure for paying inside after a certain hour, and the laminate had begun to peel at one corner and curl slightly away from the card beneath. The concrete underfoot was stained with old oil in irregular patterns that had been there long enough to have become simply a feature of the surface, like the grain in wood. A car pulled in, stopped at pump two, and the driver got out and stood for a moment reading the instructions on the screen before beginning. The process took several minutes. The driver did not look around. When the transaction was complete, the driver returned to the car and reversed slowly out of the bay and joined the highway heading north, and the forecourt was as it had been.
        """,

        // 3 — A laundromat on a Tuesday night
        """
        Six of the twelve machines along the left wall were running, and their combined sound was a kind of low roar that you stopped noticing after the first few minutes, or rather that you continued to notice only as a background against which other smaller sounds became more audible. The fluorescent light above the third machine from the end had a slight flicker, not a dramatic flicker, nothing that would have prompted anyone to complain, but a barely perceptible dimming and brightening that repeated at irregular intervals. The plastic chairs along the opposite wall were orange and had been there since at least the mid-eighties and had acquired, over the decades, a particular quality of surface that was neither smooth nor textured but somewhere in between. A woman sat in one of the chairs near the door, not the closest chair to the door but the second one, and she had her arms folded in her lap and was not reading or using her phone. She was simply waiting, in the practiced way of someone who had learned to wait without effort. On top of the row of dryers, someone had left a single white sock and a fabric softener sheet. The sock had been there for at least three visits, which was probably a week, and no one had moved it. The change machine on the back wall accepted dollar bills and returned quarters, and it made a distinct clunking sound each time a quarter dropped into the tray, which was the loudest discrete sound in the room aside from the door opening. The floor near the drain in the center of the room was slightly damp. A bulletin board beside the attendant window had several papers pinned to it at various angles, announcements mostly, some of them overlapping, the oldest ones yellowed at the edges. The attendant was not visible. A dryer in the corner finished its cycle and the tumbling inside slowed and stopped, and a small red light changed to green, and the room was briefly quieter and then seemed the same as before.
        """,

        // 4 — A hospital waiting room at midnight
        """
        The chairs were arranged in rows that faced a wall-mounted television, which was showing something with the sound turned low, a nature programme perhaps, or a documentary of the kind that involves slow aerial footage and a narrator speaking in a measured voice. The subtitles were on and scrolled across the bottom of the screen in white text on a dark band. A woman near the window had fallen asleep in her chair, her head tilted slightly to the left, her coat folded over her lap. The coat was a dark green wool. Near the vending machine, a man sat forward with his elbows on his knees, looking at the floor between his shoes. He had been in the same position for some time. The vending machine offered a range of items in lettered rows, and one of the items in row C, a packet of crisps, was hanging at an angle that suggested it had not dropped fully during a previous purchase and might or might not fall if another packet was selected from the same row. The ceiling was drop tile with embedded lighting that was somewhat dimmer than during the day hours, though it was difficult to say exactly when the change had occurred. A water cooler near the corridor leading to the wards produced a periodic gurgling sound followed by a silence, and then the gurgling again. Someone had placed a paper cup on the small ledge beside the water cooler but the cup was empty. The television changed to a commercial and then back to the programme. Outside the windows on the south side of the waiting room, the car park was lit by tall orange sodium lamps that made all colours appear slightly different than they were. A taxi idled in the drop-off bay without a passenger. The driver had his window down a few inches. The vending machine's internal light stayed on.
        """,

        // 5 — A secondary school at night, the summer before term starts
        """
        The corridors were the kind of long and the kind of wide that seem to be a requirement in buildings designed for children who must pass each other in large numbers at the same time, and at this hour they were empty in both directions, the lockers along the walls closed and latched. A fire-exit sign at the far end of the main corridor cast a thin red light onto the ceiling tiles directly above it. The classrooms that could be seen through the narrow rectangular windows in their doors were dark, the chairs up on the desks in the way they are left at the end of the school year, each chair balanced on a desktop with its legs pointing upward. A clock on the wall of the corridor near the administrative offices showed the correct time, or what appeared to be the correct time, the second hand moving in its usual even steps. The gymnasium at the back of the building smelled of rubber and floor polish and the particular staleness of large enclosed spaces. The basketball hoops at either end hung at their regulation height, their nets intact though slightly discolored from the winter condensation that had come through the high clerestory windows. A score sheet from a tournament in February was still attached to a clip on the wall near the bleachers. The numbers on it were faint. The sports equipment had been locked away in the storage cupboard for the summer and the cupboard was padlocked. In the science corridor upstairs, several of the periodic table posters were still taped to the walls outside the labs, their colors slightly bleached by months of sunlight from the south-facing windows. The element tin was printed at square number fifty. The school's main entrance doors, double and glass, reflected the empty driveway back at themselves in a dark mirror. A sparrow had built a small nest in the gutter above the bicycle shed, and the nest was unoccupied now that the eggs had long hatched and the young had gone.
        """,

        // 6 — A botanical garden after closing
        """
        The glass houses were the last of the Victorian ones in the county that had not been converted or demolished and they sat in the middle of the garden grounds in their arrangement of interconnected domes and long rectangular wings, the glass panels held in iron frames that had been repainted many times over the decades but which still showed, in certain angles of light, the slight irregularities of the original casting. Inside the largest dome, the tropical plants had grown to the height that tropical plants grow when left to grow without obstruction, and their leaves in the darkness were various shades of a darkness that was not quite the same as the darkness outside. The temperature inside was several degrees warmer than the night air and the humidity was perceptibly different in a way that was immediately apparent to anyone who entered from the garden path. A small pool in the center of the dome held water lily pads that were closed for the night, their flowers furled to tight cones, and the water below them was still and without reflection. The stone path through the garden beds was narrow in places where the edging plants had encroached over the years, and it passed under a pergola that was covered with a wisteria that was not in bloom at this time of year and whose woody stems were thick and branching and crossed each other in an intricate pattern that cast a complicated shadow in daylight. A compost enclosure near the working sheds contained matter in various stages of its transformation. A watering can had been left on a bench near the rose garden, its spout pointing away from the path. The garden gate at the south entrance was closed and the latch was down. A security lamp activated briefly in response to a small animal passing along the perimeter wall and then went dark again.
        """,

        // 7 — A provincial railway station at half past three in the morning
        """
        The station had been built in 1902 according to the plaque that had been affixed to the exterior wall at some point in the subsequent decades, and the main hall still had its original ceiling, which was high and arched and tiled in cream and brown in a geometric pattern that was not particularly remarkable but which was intact. The ticket windows were closed and shuttered with rolling metal grilles that had keyholes in them. A clock mounted above the shuttered windows showed the time in the large numerals appropriate to a room of that size. The waiting benches, which were of the heavy wooden variety with arm rests that divided them into individual seats, were mostly empty except for a man sleeping on the bench nearest the corridor leading to platform two, his rucksack beside him on the floor, one strap looped around his ankle. A vending machine in the alcove beside the left luggage office offered hot drinks and made a faint warming sound, its internal heating element doing its slow work. The departures board was electronic and showed the next service, which was a stopping train due at five forty-seven, its origin city and the various stations it would pass through listed in white letters on the dark ground. Platform one was accessible through a set of double doors that stood open and beyond them the platform extended in both directions to its ends, lit by a series of bracket lamps that threw pools of orange light at intervals on the concrete. The tracks were dark and quiet and the metal of them reflected nothing in this light. A pigeon that had roosted in the ironwork of the roof structure shifted slightly and was still. The air smelled of something industrial and something dusty and something else that was simply the smell of stone buildings in the night, which is a particular smell that has no name.
        """,

        // 8 — A hardware store just before opening
        """
        The loading bay at the back of the store was where the morning generally began, with the delivery lorry whose driver had the same route on Tuesdays and Thursdays and who reversed the vehicle with a competence born of many years of practice into a space that appeared only just large enough. But it was not yet time for the delivery, and the bay door was still down, the corrugated metal panel with its handle chain hanging vertically. The store itself was dim with the emergency lighting that remained on all night, and the aisles were in their familiar arrangement, hardware and fixings in the first section, plumbing in the second, electrical in the third, timber and sheet material at the far end where the ceiling was higher to accommodate the racking. The tins of paint were stacked on shelves in an order that was not alphabetical by colour name but organized by the system the manager had developed, which accounted for the frequency with which particular shades were requested and placed those colours at the most accessible heights. A sample card rack near the paint mixing station held hundreds of small rectangles of colour, each labelled with a name. Some of the names were descriptive, some were evocative, some seemed to have no obvious relation to the colour they named. The mixing machine sat behind the counter with its paddle mechanism at rest. On the trade counter at the back, a clipboard held a list of orders ready for collection, each with a name and a phone number and a set of items. The list had been prepared the previous afternoon. The telephone beside the clipboard was not ringing. A strip of flypaper hung from the light fitting near the storage office and was very still.
        """,

        // 9 — A university campus on a Sunday in February
        """
        The path that ran from the south gate past the humanities building and across the open square to the library was paved in the same type of brick that had been used throughout the central campus, a dull red brick that absorbed moisture in wet weather and dried to a lighter shade in dry, and at this time of the morning the bricks were wet and dark from the overnight frost that had partly thawed and left the surface neither icy nor dry but simply damp. The humanities building was the older of the two similar buildings on that side of the square and had a clock tower that had been inoperative for seventeen months. The face of the clock was visible from the path and showed a time that was not the current time but which had become, for the regular users of the path, simply a feature of the landscape, like the shape of the building itself. The library was closed and the lights in its reading rooms were off except for the one on the second floor that was left on for some reason that the staff had debated and not resolved. The square between the buildings had benches arranged at intervals and a shallow stone basin that served as a fountain in the warmer months but which had been drained in November and stood dry and leaf-filled. A bicycle was locked to the railing near the east side of the square, its rear wheel slightly flat. No one had come to claim it in several days. The notice boards fixed to the wall of the humanities building under the shallow overhang contained papers and cards and posters pinned at various angles and in some cases overlapping, events and opportunities and lost items, some of which were current and some of which had passed. The wind moved across the square at a low angle and did not particularly disturb any of them.
        """,

        // 10 — A suburban cul-de-sac at four in the morning
        """
        The houses on the cul-de-sac were all of the same period and the same approximate size and had the variations in detail, a different porch style here, an additional dormer window there, that builders add to prevent the appearance of complete uniformity and which over the years accumulate further variation from the individual choices of successive occupants. The streetlamp at the turning circle cast its light over the nearest three driveways and the cars that stood in them, the light touching the roofs of the cars and the tops of the hedges and the upper portion of the cul-de-sac sign, which was weathered but legible. The gardens behind their low front walls were dark and still, the grass wet, the plants in their various states of dormancy or slow winter growth. A cat sat on the bonnet of a dark saloon in the third driveway, its body compact, its tail wrapped around its feet. It was not looking at anything in particular. A house toward the curve of the cul-de-sac had a light on in an upstairs room, the curtains drawn, the light diffuse and yellowish through the fabric. The light had been on since before midnight. An empty green recycling bin had been left at the end of one driveway and had blown slightly off center and now stood at a small angle. Somewhere on the adjacent street, which ran parallel to the cul-de-sac and was connected to it by a narrow pedestrian path between two back gardens, a car passed without slowing, its engine sound arriving first and then the brief brightness of its headlights on the far wall of the turning circle and then the sound diminishing. The cat did not move. The bin stood at its angle. The upstairs light continued in its diffuse way to fill the curtain with a pale even yellow. Everything else remained as it was.
        """
    ]
}
